# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm run build

workflows:
  deploy-ocketeo:
    jobs:
      - build