apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend

spec:
  replicas: 5

  selector:
    matchLabels:
      app: blog-frontend

  minReadySeconds: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend-ctr
          image: kinng007/kin-blog-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend-svc

spec:
  type: NodePort

  ports:
    - port: 80
      protocol: TCP

  selector:
    app: blog-frontend
